name: '01 build'

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
            cd 01.hw-cicd
            mkdir build && cd build
            cmake ..
            cmake --build .
